//
//  CategoryViewer.swift
//  The Spy
//
//  Created by Julian Schumacher on 14.06.24.
//

import SwiftUI

struct CategoryViewer: View {
    
    let json : [String : [String]]
    
    internal init() {
        do {
            json = try JSONSerialization.jsonObject(with: NSDataAsset(name: "Words")!.data, options: [.topLevelDictionaryAssumed]) as! [String : [String]]
        } catch {
            json = [:]
            print("Error")
        }
    }
    
    var body: some View {
        VStack {
            List {
                ForEach(json.sorted(by: { $0.key > $1.key } ), id: \.key) {
                    category, words in
                    Section(category) {
                        ForEach(words, id: \.hashValue) {
                            word in
                            Text(word)
                        }
                    }
                }
                Section {
                    // Nothing
                } footer: {
                    // TODO: add ChatGPT Logo
                    Text("Generated by ChatGPT")
                }
            }
        }
        .navigationTitle("Categories")
    }
}

#Preview {
    CategoryViewer()
}
